name: Check and Create Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Get package.json version
      id: get_version
      run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

    - name: Get latest release version
      id: get_release
      run: |
        curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name' > latest_release.txt

    - name: Compare versions
      id: compare_versions
      run: |
        if [ "$(cat latest_release.txt)" != "$PACKAGE_VERSION" ]; then
          echo "Version mismatch"
          echo "create_release=true" >> $GITHUB_ENV
        else
          echo "Version matches"
          echo "create_release=false" >> $GITHUB_ENV
        fi

    - name: Create new release
      if: env.create_release == 'true'
      run: |
        CURRENT_DATE=$(TZ='Asia/Shanghai' date +'%Y-%m-%d  %H:%M')
        # 获取version-log.md中最新版本的内容
        awk '/^## / {if (p) {exit}; p=1; next} p {print}' version-log.md > release_notes.tmp
        gh release create "$PACKAGE_VERSION" \
        -t "$PACKAGE_VERSION" \
        -F release_notes.tmp \
        --assets main.js,manifest.json,styles.css
        rm release_notes.tmp
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}